### ISSUE TITLE
String Index Out Of Range Error

### ISSUE THREAD

**Issue by swanserquack** [4drian3d/ChatRegulator#7]
Hi,
Just recently started using your plugin on my velocity instance. Recently I have had this error popup on my logs and I'm not sure if this effects the actual running of the plugin. I have changed nothing in the config.

Error: 
[19:36:52 ERROR]: Couldn't pass CommandExecuteEvent to chatregulator
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
        at java.lang.String.charAt(String.java:711) ~[?:?]
        at net.dreamerzero.chatregulator.modules.Replacer.addFinalDot(Replacer.java:21) ~[?:?]
        at net.dreamerzero.chatregulator.modules.Replacer.applyFormat(Replacer.java:28) ~[?:?]
        at net.dreamerzero.chatregulator.listener.command.CommandListener.onCommand(CommandListener.java:121) ~[?:?]
        at net.dreamerzero.chatregulator.listener.command.Lmbda$19.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

Thanks,
@swanserquack

**Comment by 4drian3d** [comment]
I just fixed the bug. But currently I have made many changes to the project and I can't release a stable release yet, but I will prioritize to release a new version very soon.

**Comment by 4drian3d** [comment]
I just released the new version https://github.com/4drian3d/ChatRegulator/releases/tag/1.4.0

If you have configured messages, in this update they were moved to a separate file and more customizable messages were added.

**Comment by swanserquack** [comment]
Okay, thanks for all your help on this
